version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - "type: Chore"
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.15
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.17
  - dependency-name: "@babel/cli"
    versions:
    - 7.13.10
    - 7.13.14
    - 7.13.16
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.5
    - 24.1.6
    - 24.1.7
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.10
    - 7.13.15
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.8
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: webpack-merge
    versions:
    - 5.7.3
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: jest
    versions:
    - 26.6.3
  - dependency-name: babel-jest
    versions:
    - 26.6.3
  - dependency-name: jest-cli
    versions:
    - 26.6.3
  - dependency-name: yargs-parser
    versions:
    - 5.0.1
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - "type: Chore"
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: ini
    versions:
    - 1.3.7
