name: Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        name: Test Suite
        runs-on: ubuntu-latest

        steps:
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-npm-
                      ${{ runner.OS }}-

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint

            - name: Transpile to ES5
              run: npm run transpile:cjs

            - name: ES5 tests
              run: npm run test:es5

            - name: Normal tests
              run: npm run test

            - name: Performance tests
              run: npm run test:perf

            - name: Collect coverage
              run: npx codecov
